server:
  port: 8080
  forward-headers-strategy: framework
logging:
  level:
    root: INFO
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    com.dchans.api.admin.mapper: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.transaction: DEBUG