server:
  port: 443
  forward-headers-strategy: framework
  ssl:
    key-store: /app/keystore.p12
    key-store-password: eum0923^^
    key-store-type: PKCS12
    key-alias: amita-keystore
logging:
  level:
    org.springframework: INFO
    org.apache.ibatis: INFO
    com.dchans.api.admin.mapper: INFO